export const searchSuggestions = [
  { name: "Vincent van Gogh", type: "artist" },
  { name: "Pablo Picasso", type: "artist" },
  { name: "Claude Monet", type: "artist" },
  { name: "Salvador Dalí", type: "artist" },
  { name: "Andy Warhol", type: "artist" },
  { name: "Wassily Kandinsky", type: "artist" },
  { name: "Frida Kahlo", type: "artist" },
  { name: "Mark Rothko", type: "artist" },
  { name: "Jackson Pollock", type: "artist" },
  { name: "Henri Matisse", type: "artist" },
  { name: "Romanticism", type: "style" },
  { name: "Realism", type: "style" },
  { name: "Impressionism", type: "style" },
  { name: "Post-Impressionism", type: "style" },
  { name: "Cubism", type: "style" },
  { name: "Expressionism", type: "style" },
  { name: "Fauvism", type: "style" },
  { name: "Art Nouveau", type: "style" },
  { name: "Surrealism", type: "style" },
  { name: "Abstract Expressionism", type: "style" },
  { name: "Pop Art", type: "style" },
  { name: "Minimalism", type: "style" },
  { name: "Conceptual Art", type: "style" },
  { name: "Installation Art", type: "style" },
  { name: "Performance Art", type: "style" },
  { name: "Digital Art", type: "style" },
];
